### ISSUE TITLE
Collision Question

### ISSUE THREAD

**Issue by flamendless** [pelevesque/draft#2]
Hi, i would like to know if there's some way i could use these shapes and have collisions with them. Collisions like point to shape, shape to shape, etc.

**Comment by pelevesque** [comment]
The functions in this library all do 2 things. 1) They draw the shape. (optional) 2) They return the shape points.

If you want to do collision detection, you can take the returned shape points then use some other library to do collision detection. This library does not do that.

**Comment by flamendless** [comment]
Thanks!
